# Generated by Django 6.0.3 on 2026-03-30 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='prioridade',
            field=models.CharField(choices=[('URGENTE', 'Urgente'), ('NAO_URGENTE', 'Não urgente')], default='NAO_URGENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='carro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
